### ISSUE TITLE
Is it possible to use this plugin with ANY Bluetooth printer in PGB?

### ISSUE THREAD

**Issue by bottasergio** [sampetrosov/SignaturePrinter#1]
Is this plugin useful for any bluetooth printer in PhoneGap Build (Android)?

**Comment by sampetrosov** [comment]
@bottasergio I have tested this with Star Mobile(T300I), Woosim(Porti-W40) and Thermal ESC/POS printer(http://www.ebay.com/itm/POS-5802-Bluetooth-Thermal-Receipt-Printer-58mm-USB-POS-Ticket-Printer-/122520829074?hash=item1c86cf7c92:g:kaQAAOSw3v5YtOK~).

**Comment by bottasergio** [comment]
How should I include your plugin in my web.config? 

 

<plugin name="cordova-plugin-android-support-v4" spec="21.0.1" />

<plugin name="cordova-plugin-device" spec="1.1.2" />

...

<plugin name="..."  />

¿?

 

De: Samvel Petrosov [mailto:notifications@github.com] 
Enviado el: martes, 27 de junio de 2017 13:19
Para: sampetrosov/SignaturePrinter
CC: bottasergio; Mention
Asunto: Re: [sampetrosov/SignaturePrinter] Is it possible to use this plugin with ANY Bluetooth printer in PGB? (#1)

 

@bottasergio <https://github.com/bottasergio>  I have tested this with Star Mobile(T300I), Woosim(Porti-W40) and Thermal ESC/POS printer(http://www.ebay.com/itm/POS-5802-Bluetooth-Thermal-Receipt-Printer-58mm-USB-POS-Ticket-Printer-/122520829074?hash=item1c86cf7c92:g:kaQAAOSw3v5YtOK~).

**Comment by sampetrosov** [comment]
@bottasergio I don't know how to work with PhoneGap on Cordova you can install plugin to project by running cordova plugin add SignaturePrinter in Command Line
