### ISSUE TITLE
printSignature

### ISSUE THREAD

**Issue by lansas** [sampetrosov/SignaturePrinter#3]
Could you please give me an example to use imageColors for printSignature function?

window.printSignature(imageColors,width,height,successCallback);//imageColors is int array of pixels(ARGB)

In the future, do you think to improve to print base64 encoded image?

**Comment by sampetrosov** [comment]
Here is example of using window.pringSignature:


function getPixel(data,width,x,y){
    var i=(x+y*width)*4;
    var col = data[i+3]<<24;
    col += data[i]<<16;
    col += data[i+1]<<8;
    col +=data[i+2];
    return col;
}
	
function printSign(imageData, height, width, success, failure) {
    var colors = [];
    for(var i =0;i<height;i++)
    {
        for(var j=0;j<width;j++)
        {
            colors.push(getPixel(imageData,width,j,i));
        }
    }
    window.printSignature(colors,width,height,success, failure)
}


var imgData = _canvas._ctx.getImageData(0, 0, _canvas.width, _canvas.height);

printSign(imgData.data, 
			imgData.height, 
			imgData.width,
			function (data) {
				console.log('Success',data);
			},
			function (status) {
				console.log('Error',status)
			});

Currently I'm not having enough time to write printing from base64. But I'm planning to do that

**Comment by lansas** [comment]
thanks. Do you plan to list printers around bluetooth printers?

**Comment by sampetrosov** [comment]
@lansas  I don't understand what you mean

**Comment by lansas** [comment]
like that code in https://github.com/srehanuddin/Cordova-Plugin-Bluetooth-Printer
##Usage Get list of paired bluetooth printers

BTPrinter.list(function(data){
        console.log("Success");
        console.log(data); //list of printer in data array
    },function(err){
        console.log("Error");
        console.log(err);
    })

**Comment by sampetrosov** [comment]
@lansas Yeah, I have the code already in this plugin, I will do it in the next review of the plugin.

**Comment by lansas** [comment]
Hello Sam,
above code I see colors array (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1934655932, -11434557, -11566659, -11566659,................) in printSign function, but when I was sending window.printSignature(colors,width,height,success, failure) I get that failure: _Error in printImage();Message Attempt to invoke virtual method 'void java.io.OutputStream.write(byte[])' on a null object reference_

Here is my code to get imgData.data for printSign function:

var canvas = document.getElementById('myCanvas');
var ctx = canvas.getContext('2d');
var base64 ='data:image/png;base64,iVBOR...........................uQmCC'; //base64 string example

    var image = new Image();
    image.onload = (function(canvas, ctx){ return function(){
            ctx.drawImage(this, 0, 0);
            //now we can finally get a Uint8ClampedArray
            var imgData = ctx.getImageData(0, 0, 34, 34);

            printSign(imgData.data,imgData.height,imgData.width,function (data) {
                console.log(data);
            },function (status) {
                console.log(status); // failure Error in printImage();Message Attempt to invoke virtual method 'void java.io.OutputStream.write(byte[])' on a null object reference
            });
        };
    })(canvas, ctx);
    image.src = base64;
